version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: appsynex_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appsynex
      MYSQL_USER: appsynex_user
      MYSQL_PASSWORD: appsynex_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appsynex_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    build: .
    container_name: appsynex_api
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      # Database connection - Trong Docker network
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: appsynex_user
      DB_PASS: appsynex_password
      DB_NAME: appsynex
      # Server config
      PORT: 8080
      ENV: development
      # JWT
      JWT_SECRET: your_super_secret_jwt_key_here
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - appsynex_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: appsynex_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - appsynex_network

volumes:
  mysql_data:

networks:
  appsynex_network:
    driver: bridge